version: "3.8"
services:
    minio:
        image: minio/minio:latest
        container_name: minio-container
        environment:
            - MINIO_ROOT_USER=test
            - MINIO_ROOT_PASSWORD=test
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./minio/data:/data
    postgresql:
        image: postgres:latest
        container_name: postgresql-container
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=mydatabase
        ports:
            - 5432:5432
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
